name: Auto Create Chat Room

on:
  issues:
    types: [opened]

jobs:
  chattery:
    name: chattery
    runs-on: ubuntu-latest
    steps:
      - name: post comment
        uses: lukejacksonn/chattery@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
